/*
 * Copyright (C) 2013 Schlichtherle IT Services.
 * All rights reserved. Use is subject to license terms.
 */
package de.schlichtherle.demo.guice.job;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.*;
import javax.inject.Provider;
import static org.junit.Assert.*;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

/**
 * @author Christian Schlichtherle
 */
@RunWith(Parameterized.class)
public class TimeOfDayJobTest {

    @Parameters
    public static Iterable<Object[]> data() {
        return Arrays.asList(new Object[][] {
            { Locale.GERMANY, 0, 0, 0, "Beim nächsten Ton ist es null Uhr, null Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 0, 0, 1, "Beim nächsten Ton ist es null Uhr, null Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 0, 0, 2, "Beim nächsten Ton ist es null Uhr, null Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 0, 0, 3, "Beim nächsten Ton ist es null Uhr, null Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 0, 1, 0, "Beim nächsten Ton ist es null Uhr, eine Minute und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 0, 1, 1, "Beim nächsten Ton ist es null Uhr, eine Minute und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 0, 1, 2, "Beim nächsten Ton ist es null Uhr, eine Minute und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 0, 1, 3, "Beim nächsten Ton ist es null Uhr, eine Minute und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 0, 2, 0, "Beim nächsten Ton ist es null Uhr, zwei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 0, 2, 1, "Beim nächsten Ton ist es null Uhr, zwei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 0, 2, 2, "Beim nächsten Ton ist es null Uhr, zwei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 0, 2, 3, "Beim nächsten Ton ist es null Uhr, zwei Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 0, 3, 0, "Beim nächsten Ton ist es null Uhr, drei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 0, 3, 1, "Beim nächsten Ton ist es null Uhr, drei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 0, 3, 2, "Beim nächsten Ton ist es null Uhr, drei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 0, 3, 3, "Beim nächsten Ton ist es null Uhr, drei Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 0, 0, "Beim nächsten Ton ist es ein Uhr, null Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 0, 1, "Beim nächsten Ton ist es ein Uhr, null Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 1, 0, 2, "Beim nächsten Ton ist es ein Uhr, null Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 0, 3, "Beim nächsten Ton ist es ein Uhr, null Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 1, 0, "Beim nächsten Ton ist es ein Uhr, eine Minute und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 1, 1, "Beim nächsten Ton ist es ein Uhr, eine Minute und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 1, 1, 2, "Beim nächsten Ton ist es ein Uhr, eine Minute und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 1, 3, "Beim nächsten Ton ist es ein Uhr, eine Minute und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 2, 0, "Beim nächsten Ton ist es ein Uhr, zwei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 2, 1, "Beim nächsten Ton ist es ein Uhr, zwei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 1, 2, 2, "Beim nächsten Ton ist es ein Uhr, zwei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 2, 3, "Beim nächsten Ton ist es ein Uhr, zwei Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 3, 0, "Beim nächsten Ton ist es ein Uhr, drei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 3, 1, "Beim nächsten Ton ist es ein Uhr, drei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 1, 3, 2, "Beim nächsten Ton ist es ein Uhr, drei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 1, 3, 3, "Beim nächsten Ton ist es ein Uhr, drei Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 0, 0, "Beim nächsten Ton ist es zwei Uhr, null Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 0, 1, "Beim nächsten Ton ist es zwei Uhr, null Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 2, 0, 2, "Beim nächsten Ton ist es zwei Uhr, null Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 0, 3, "Beim nächsten Ton ist es zwei Uhr, null Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 1, 0, "Beim nächsten Ton ist es zwei Uhr, eine Minute und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 1, 1, "Beim nächsten Ton ist es zwei Uhr, eine Minute und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 2, 1, 2, "Beim nächsten Ton ist es zwei Uhr, eine Minute und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 1, 3, "Beim nächsten Ton ist es zwei Uhr, eine Minute und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 2, 0, "Beim nächsten Ton ist es zwei Uhr, zwei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 2, 1, "Beim nächsten Ton ist es zwei Uhr, zwei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 2, 2, 2, "Beim nächsten Ton ist es zwei Uhr, zwei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 2, 3, "Beim nächsten Ton ist es zwei Uhr, zwei Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 3, 0, "Beim nächsten Ton ist es zwei Uhr, drei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 3, 1, "Beim nächsten Ton ist es zwei Uhr, drei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 2, 3, 2, "Beim nächsten Ton ist es zwei Uhr, drei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 2, 3, 3, "Beim nächsten Ton ist es zwei Uhr, drei Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 0, 0, "Beim nächsten Ton ist es drei Uhr, null Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 0, 1, "Beim nächsten Ton ist es drei Uhr, null Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 3, 0, 2, "Beim nächsten Ton ist es drei Uhr, null Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 0, 3, "Beim nächsten Ton ist es drei Uhr, null Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 1, 0, "Beim nächsten Ton ist es drei Uhr, eine Minute und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 1, 1, "Beim nächsten Ton ist es drei Uhr, eine Minute und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 3, 1, 2, "Beim nächsten Ton ist es drei Uhr, eine Minute und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 1, 3, "Beim nächsten Ton ist es drei Uhr, eine Minute und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 2, 0, "Beim nächsten Ton ist es drei Uhr, zwei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 2, 1, "Beim nächsten Ton ist es drei Uhr, zwei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 3, 2, 2, "Beim nächsten Ton ist es drei Uhr, zwei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 2, 3, "Beim nächsten Ton ist es drei Uhr, zwei Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 3, 0, "Beim nächsten Ton ist es drei Uhr, drei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 3, 1, "Beim nächsten Ton ist es drei Uhr, drei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 3, 3, 2, "Beim nächsten Ton ist es drei Uhr, drei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 3, 3, 3, "Beim nächsten Ton ist es drei Uhr, drei Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 0, 0, "Beim nächsten Ton ist es zwölf Uhr, null Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 0, 1, "Beim nächsten Ton ist es zwölf Uhr, null Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 12, 0, 2, "Beim nächsten Ton ist es zwölf Uhr, null Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 0, 3, "Beim nächsten Ton ist es zwölf Uhr, null Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 1, 0, "Beim nächsten Ton ist es zwölf Uhr, eine Minute und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 1, 1, "Beim nächsten Ton ist es zwölf Uhr, eine Minute und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 12, 1, 2, "Beim nächsten Ton ist es zwölf Uhr, eine Minute und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 1, 3, "Beim nächsten Ton ist es zwölf Uhr, eine Minute und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 2, 0, "Beim nächsten Ton ist es zwölf Uhr, zwei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 2, 1, "Beim nächsten Ton ist es zwölf Uhr, zwei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 12, 2, 2, "Beim nächsten Ton ist es zwölf Uhr, zwei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 2, 3, "Beim nächsten Ton ist es zwölf Uhr, zwei Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 3, 0, "Beim nächsten Ton ist es zwölf Uhr, drei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 3, 1, "Beim nächsten Ton ist es zwölf Uhr, drei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 12, 3, 2, "Beim nächsten Ton ist es zwölf Uhr, drei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 12, 3, 3, "Beim nächsten Ton ist es zwölf Uhr, drei Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 0, 0, "Beim nächsten Ton ist es dreizehn Uhr, null Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 0, 1, "Beim nächsten Ton ist es dreizehn Uhr, null Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 13, 0, 2, "Beim nächsten Ton ist es dreizehn Uhr, null Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 0, 3, "Beim nächsten Ton ist es dreizehn Uhr, null Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 1, 0, "Beim nächsten Ton ist es dreizehn Uhr, eine Minute und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 1, 1, "Beim nächsten Ton ist es dreizehn Uhr, eine Minute und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 13, 1, 2, "Beim nächsten Ton ist es dreizehn Uhr, eine Minute und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 1, 3, "Beim nächsten Ton ist es dreizehn Uhr, eine Minute und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 2, 0, "Beim nächsten Ton ist es dreizehn Uhr, zwei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 2, 1, "Beim nächsten Ton ist es dreizehn Uhr, zwei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 13, 2, 2, "Beim nächsten Ton ist es dreizehn Uhr, zwei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 2, 3, "Beim nächsten Ton ist es dreizehn Uhr, zwei Minuten und drei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 3, 0, "Beim nächsten Ton ist es dreizehn Uhr, drei Minuten und null Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 3, 1, "Beim nächsten Ton ist es dreizehn Uhr, drei Minuten und eine Sekunde. PIIIEP.\n" },
            { Locale.GERMANY, 13, 3, 2, "Beim nächsten Ton ist es dreizehn Uhr, drei Minuten und zwei Sekunden. PIIIEP.\n" },
            { Locale.GERMANY, 13, 3, 3, "Beim nächsten Ton ist es dreizehn Uhr, drei Minuten und drei Sekunden. PIIIEP.\n" },

            { Locale.UK, 0, 0, 0, "At the third stroke, it will be twelve o'clock precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 0, 1, "At the third stroke, it will be twelve o'clock and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 0, 2, "At the third stroke, it will be twelve o'clock and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 0, 3, "At the third stroke, it will be twelve o'clock and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 1, 0, "At the third stroke, it will be twelve one precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 1, 1, "At the third stroke, it will be twelve one and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 1, 2, "At the third stroke, it will be twelve one and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 1, 3, "At the third stroke, it will be twelve one and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 2, 0, "At the third stroke, it will be twelve two precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 2, 1, "At the third stroke, it will be twelve two and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 2, 2, "At the third stroke, it will be twelve two and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 2, 3, "At the third stroke, it will be twelve two and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 3, 0, "At the third stroke, it will be twelve three precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 3, 1, "At the third stroke, it will be twelve three and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 3, 2, "At the third stroke, it will be twelve three and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 0, 3, 3, "At the third stroke, it will be twelve three and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 0, 0, "At the third stroke, it will be one o'clock precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 0, 1, "At the third stroke, it will be one o'clock and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 0, 2, "At the third stroke, it will be one o'clock and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 0, 3, "At the third stroke, it will be one o'clock and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 1, 0, "At the third stroke, it will be one one precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 1, 1, "At the third stroke, it will be one one and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 1, 2, "At the third stroke, it will be one one and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 1, 3, "At the third stroke, it will be one one and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 2, 0, "At the third stroke, it will be one two precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 2, 1, "At the third stroke, it will be one two and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 2, 2, "At the third stroke, it will be one two and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 2, 3, "At the third stroke, it will be one two and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 3, 0, "At the third stroke, it will be one three precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 3, 1, "At the third stroke, it will be one three and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 3, 2, "At the third stroke, it will be one three and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 1, 3, 3, "At the third stroke, it will be one three and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 0, 0, "At the third stroke, it will be two o'clock precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 0, 1, "At the third stroke, it will be two o'clock and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 0, 2, "At the third stroke, it will be two o'clock and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 0, 3, "At the third stroke, it will be two o'clock and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 1, 0, "At the third stroke, it will be two one precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 1, 1, "At the third stroke, it will be two one and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 1, 2, "At the third stroke, it will be two one and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 1, 3, "At the third stroke, it will be two one and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 2, 0, "At the third stroke, it will be two two precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 2, 1, "At the third stroke, it will be two two and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 2, 2, "At the third stroke, it will be two two and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 2, 3, "At the third stroke, it will be two two and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 3, 0, "At the third stroke, it will be two three precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 3, 1, "At the third stroke, it will be two three and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 3, 2, "At the third stroke, it will be two three and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 2, 3, 3, "At the third stroke, it will be two three and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 0, 0, "At the third stroke, it will be three o'clock precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 0, 1, "At the third stroke, it will be three o'clock and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 0, 2, "At the third stroke, it will be three o'clock and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 0, 3, "At the third stroke, it will be three o'clock and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 1, 0, "At the third stroke, it will be three one precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 1, 1, "At the third stroke, it will be three one and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 1, 2, "At the third stroke, it will be three one and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 1, 3, "At the third stroke, it will be three one and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 2, 0, "At the third stroke, it will be three two precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 2, 1, "At the third stroke, it will be three two and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 2, 2, "At the third stroke, it will be three two and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 2, 3, "At the third stroke, it will be three two and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 3, 0, "At the third stroke, it will be three three precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 3, 1, "At the third stroke, it will be three three and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 3, 2, "At the third stroke, it will be three three and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 3, 3, 3, "At the third stroke, it will be three three and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 0, 0, "At the third stroke, it will be twelve o'clock precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 0, 1, "At the third stroke, it will be twelve o'clock and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 0, 2, "At the third stroke, it will be twelve o'clock and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 0, 3, "At the third stroke, it will be twelve o'clock and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 1, 0, "At the third stroke, it will be twelve one precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 1, 1, "At the third stroke, it will be twelve one and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 1, 2, "At the third stroke, it will be twelve one and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 1, 3, "At the third stroke, it will be twelve one and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 2, 0, "At the third stroke, it will be twelve two precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 2, 1, "At the third stroke, it will be twelve two and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 2, 2, "At the third stroke, it will be twelve two and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 2, 3, "At the third stroke, it will be twelve two and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 3, 0, "At the third stroke, it will be twelve three precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 3, 1, "At the third stroke, it will be twelve three and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 3, 2, "At the third stroke, it will be twelve three and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 12, 3, 3, "At the third stroke, it will be twelve three and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 0, 0, "At the third stroke, it will be one o'clock precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 0, 1, "At the third stroke, it will be one o'clock and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 0, 2, "At the third stroke, it will be one o'clock and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 0, 3, "At the third stroke, it will be one o'clock and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 1, 0, "At the third stroke, it will be one one precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 1, 1, "At the third stroke, it will be one one and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 1, 2, "At the third stroke, it will be one one and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 1, 3, "At the third stroke, it will be one one and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 2, 0, "At the third stroke, it will be one two precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 2, 1, "At the third stroke, it will be one two and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 2, 2, "At the third stroke, it will be one two and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 2, 3, "At the third stroke, it will be one two and three seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 3, 0, "At the third stroke, it will be one three precisely. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 3, 1, "At the third stroke, it will be one three and one second. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 3, 2, "At the third stroke, it will be one three and two seconds. BEEP, BEEP, BEEP.\n" },
            { Locale.UK, 13, 3, 3, "At the third stroke, it will be one three and three seconds. BEEP, BEEP, BEEP.\n" },

            { Locale.US, 0, 0, 0, "Good morning. At the tone, the time will be twelve o'clock exactly. BEEP.\n" },
            { Locale.US, 0, 0, 1, "Good morning. At the tone, the time will be twelve o'clock and one second. BEEP.\n" },
            { Locale.US, 0, 0, 2, "Good morning. At the tone, the time will be twelve o'clock and two seconds. BEEP.\n" },
            { Locale.US, 0, 0, 3, "Good morning. At the tone, the time will be twelve o'clock and three seconds. BEEP.\n" },
            { Locale.US, 0, 1, 0, "Good morning. At the tone, the time will be twelve one exactly. BEEP.\n" },
            { Locale.US, 0, 1, 1, "Good morning. At the tone, the time will be twelve one and one second. BEEP.\n" },
            { Locale.US, 0, 1, 2, "Good morning. At the tone, the time will be twelve one and two seconds. BEEP.\n" },
            { Locale.US, 0, 1, 3, "Good morning. At the tone, the time will be twelve one and three seconds. BEEP.\n" },
            { Locale.US, 0, 2, 0, "Good morning. At the tone, the time will be twelve two exactly. BEEP.\n" },
            { Locale.US, 0, 2, 1, "Good morning. At the tone, the time will be twelve two and one second. BEEP.\n" },
            { Locale.US, 0, 2, 2, "Good morning. At the tone, the time will be twelve two and two seconds. BEEP.\n" },
            { Locale.US, 0, 2, 3, "Good morning. At the tone, the time will be twelve two and three seconds. BEEP.\n" },
            { Locale.US, 0, 3, 0, "Good morning. At the tone, the time will be twelve three exactly. BEEP.\n" },
            { Locale.US, 0, 3, 1, "Good morning. At the tone, the time will be twelve three and one second. BEEP.\n" },
            { Locale.US, 0, 3, 2, "Good morning. At the tone, the time will be twelve three and two seconds. BEEP.\n" },
            { Locale.US, 0, 3, 3, "Good morning. At the tone, the time will be twelve three and three seconds. BEEP.\n" },
            { Locale.US, 1, 0, 0, "Good morning. At the tone, the time will be one o'clock exactly. BEEP.\n" },
            { Locale.US, 1, 0, 1, "Good morning. At the tone, the time will be one o'clock and one second. BEEP.\n" },
            { Locale.US, 1, 0, 2, "Good morning. At the tone, the time will be one o'clock and two seconds. BEEP.\n" },
            { Locale.US, 1, 0, 3, "Good morning. At the tone, the time will be one o'clock and three seconds. BEEP.\n" },
            { Locale.US, 1, 1, 0, "Good morning. At the tone, the time will be one one exactly. BEEP.\n" },
            { Locale.US, 1, 1, 1, "Good morning. At the tone, the time will be one one and one second. BEEP.\n" },
            { Locale.US, 1, 1, 2, "Good morning. At the tone, the time will be one one and two seconds. BEEP.\n" },
            { Locale.US, 1, 1, 3, "Good morning. At the tone, the time will be one one and three seconds. BEEP.\n" },
            { Locale.US, 1, 2, 0, "Good morning. At the tone, the time will be one two exactly. BEEP.\n" },
            { Locale.US, 1, 2, 1, "Good morning. At the tone, the time will be one two and one second. BEEP.\n" },
            { Locale.US, 1, 2, 2, "Good morning. At the tone, the time will be one two and two seconds. BEEP.\n" },
            { Locale.US, 1, 2, 3, "Good morning. At the tone, the time will be one two and three seconds. BEEP.\n" },
            { Locale.US, 1, 3, 0, "Good morning. At the tone, the time will be one three exactly. BEEP.\n" },
            { Locale.US, 1, 3, 1, "Good morning. At the tone, the time will be one three and one second. BEEP.\n" },
            { Locale.US, 1, 3, 2, "Good morning. At the tone, the time will be one three and two seconds. BEEP.\n" },
            { Locale.US, 1, 3, 3, "Good morning. At the tone, the time will be one three and three seconds. BEEP.\n" },
            { Locale.US, 2, 0, 0, "Good morning. At the tone, the time will be two o'clock exactly. BEEP.\n" },
            { Locale.US, 2, 0, 1, "Good morning. At the tone, the time will be two o'clock and one second. BEEP.\n" },
            { Locale.US, 2, 0, 2, "Good morning. At the tone, the time will be two o'clock and two seconds. BEEP.\n" },
            { Locale.US, 2, 0, 3, "Good morning. At the tone, the time will be two o'clock and three seconds. BEEP.\n" },
            { Locale.US, 2, 1, 0, "Good morning. At the tone, the time will be two one exactly. BEEP.\n" },
            { Locale.US, 2, 1, 1, "Good morning. At the tone, the time will be two one and one second. BEEP.\n" },
            { Locale.US, 2, 1, 2, "Good morning. At the tone, the time will be two one and two seconds. BEEP.\n" },
            { Locale.US, 2, 1, 3, "Good morning. At the tone, the time will be two one and three seconds. BEEP.\n" },
            { Locale.US, 2, 2, 0, "Good morning. At the tone, the time will be two two exactly. BEEP.\n" },
            { Locale.US, 2, 2, 1, "Good morning. At the tone, the time will be two two and one second. BEEP.\n" },
            { Locale.US, 2, 2, 2, "Good morning. At the tone, the time will be two two and two seconds. BEEP.\n" },
            { Locale.US, 2, 2, 3, "Good morning. At the tone, the time will be two two and three seconds. BEEP.\n" },
            { Locale.US, 2, 3, 0, "Good morning. At the tone, the time will be two three exactly. BEEP.\n" },
            { Locale.US, 2, 3, 1, "Good morning. At the tone, the time will be two three and one second. BEEP.\n" },
            { Locale.US, 2, 3, 2, "Good morning. At the tone, the time will be two three and two seconds. BEEP.\n" },
            { Locale.US, 2, 3, 3, "Good morning. At the tone, the time will be two three and three seconds. BEEP.\n" },
            { Locale.US, 3, 0, 0, "Good morning. At the tone, the time will be three o'clock exactly. BEEP.\n" },
            { Locale.US, 3, 0, 1, "Good morning. At the tone, the time will be three o'clock and one second. BEEP.\n" },
            { Locale.US, 3, 0, 2, "Good morning. At the tone, the time will be three o'clock and two seconds. BEEP.\n" },
            { Locale.US, 3, 0, 3, "Good morning. At the tone, the time will be three o'clock and three seconds. BEEP.\n" },
            { Locale.US, 3, 1, 0, "Good morning. At the tone, the time will be three one exactly. BEEP.\n" },
            { Locale.US, 3, 1, 1, "Good morning. At the tone, the time will be three one and one second. BEEP.\n" },
            { Locale.US, 3, 1, 2, "Good morning. At the tone, the time will be three one and two seconds. BEEP.\n" },
            { Locale.US, 3, 1, 3, "Good morning. At the tone, the time will be three one and three seconds. BEEP.\n" },
            { Locale.US, 3, 2, 0, "Good morning. At the tone, the time will be three two exactly. BEEP.\n" },
            { Locale.US, 3, 2, 1, "Good morning. At the tone, the time will be three two and one second. BEEP.\n" },
            { Locale.US, 3, 2, 2, "Good morning. At the tone, the time will be three two and two seconds. BEEP.\n" },
            { Locale.US, 3, 2, 3, "Good morning. At the tone, the time will be three two and three seconds. BEEP.\n" },
            { Locale.US, 3, 3, 0, "Good morning. At the tone, the time will be three three exactly. BEEP.\n" },
            { Locale.US, 3, 3, 1, "Good morning. At the tone, the time will be three three and one second. BEEP.\n" },
            { Locale.US, 3, 3, 2, "Good morning. At the tone, the time will be three three and two seconds. BEEP.\n" },
            { Locale.US, 3, 3, 3, "Good morning. At the tone, the time will be three three and three seconds. BEEP.\n" },
            { Locale.US, 12, 0, 0, "Good afternoon. At the tone, the time will be twelve o'clock exactly. BEEP.\n" },
            { Locale.US, 12, 0, 1, "Good afternoon. At the tone, the time will be twelve o'clock and one second. BEEP.\n" },
            { Locale.US, 12, 0, 2, "Good afternoon. At the tone, the time will be twelve o'clock and two seconds. BEEP.\n" },
            { Locale.US, 12, 0, 3, "Good afternoon. At the tone, the time will be twelve o'clock and three seconds. BEEP.\n" },
            { Locale.US, 12, 1, 0, "Good afternoon. At the tone, the time will be twelve one exactly. BEEP.\n" },
            { Locale.US, 12, 1, 1, "Good afternoon. At the tone, the time will be twelve one and one second. BEEP.\n" },
            { Locale.US, 12, 1, 2, "Good afternoon. At the tone, the time will be twelve one and two seconds. BEEP.\n" },
            { Locale.US, 12, 1, 3, "Good afternoon. At the tone, the time will be twelve one and three seconds. BEEP.\n" },
            { Locale.US, 12, 2, 0, "Good afternoon. At the tone, the time will be twelve two exactly. BEEP.\n" },
            { Locale.US, 12, 2, 1, "Good afternoon. At the tone, the time will be twelve two and one second. BEEP.\n" },
            { Locale.US, 12, 2, 2, "Good afternoon. At the tone, the time will be twelve two and two seconds. BEEP.\n" },
            { Locale.US, 12, 2, 3, "Good afternoon. At the tone, the time will be twelve two and three seconds. BEEP.\n" },
            { Locale.US, 12, 3, 0, "Good afternoon. At the tone, the time will be twelve three exactly. BEEP.\n" },
            { Locale.US, 12, 3, 1, "Good afternoon. At the tone, the time will be twelve three and one second. BEEP.\n" },
            { Locale.US, 12, 3, 2, "Good afternoon. At the tone, the time will be twelve three and two seconds. BEEP.\n" },
            { Locale.US, 12, 3, 3, "Good afternoon. At the tone, the time will be twelve three and three seconds. BEEP.\n" },
            { Locale.US, 13, 0, 0, "Good afternoon. At the tone, the time will be one o'clock exactly. BEEP.\n" },
            { Locale.US, 13, 0, 1, "Good afternoon. At the tone, the time will be one o'clock and one second. BEEP.\n" },
            { Locale.US, 13, 0, 2, "Good afternoon. At the tone, the time will be one o'clock and two seconds. BEEP.\n" },
            { Locale.US, 13, 0, 3, "Good afternoon. At the tone, the time will be one o'clock and three seconds. BEEP.\n" },
            { Locale.US, 13, 1, 0, "Good afternoon. At the tone, the time will be one one exactly. BEEP.\n" },
            { Locale.US, 13, 1, 1, "Good afternoon. At the tone, the time will be one one and one second. BEEP.\n" },
            { Locale.US, 13, 1, 2, "Good afternoon. At the tone, the time will be one one and two seconds. BEEP.\n" },
            { Locale.US, 13, 1, 3, "Good afternoon. At the tone, the time will be one one and three seconds. BEEP.\n" },
            { Locale.US, 13, 2, 0, "Good afternoon. At the tone, the time will be one two exactly. BEEP.\n" },
            { Locale.US, 13, 2, 1, "Good afternoon. At the tone, the time will be one two and one second. BEEP.\n" },
            { Locale.US, 13, 2, 2, "Good afternoon. At the tone, the time will be one two and two seconds. BEEP.\n" },
            { Locale.US, 13, 2, 3, "Good afternoon. At the tone, the time will be one two and three seconds. BEEP.\n" },
            { Locale.US, 13, 3, 0, "Good afternoon. At the tone, the time will be one three exactly. BEEP.\n" },
            { Locale.US, 13, 3, 1, "Good afternoon. At the tone, the time will be one three and one second. BEEP.\n" },
            { Locale.US, 13, 3, 2, "Good afternoon. At the tone, the time will be one three and two seconds. BEEP.\n" },
            { Locale.US, 13, 3, 3, "Good afternoon. At the tone, the time will be one three and three seconds. BEEP.\n" },
        });
    }

    private final TimeOfDayJob job;
    private final String string;

    public TimeOfDayJobTest(
            final Locale locale,
            final int hourOfDay,
            final int minute,
            final int second,
            final String string) {
        final Provider<Date> clock = new Provider<Date>() {
            @Override public Date get() {
                Calendar cal = Calendar.getInstance();
                cal.set(Calendar.HOUR_OF_DAY, hourOfDay);
                cal.set(Calendar.MINUTE, minute);
                cal.set(Calendar.SECOND, second);
                return cal.getTime();
            }
        };
        this.job = new TimeOfDayJob(clock, locale);
        this.string = string;
    }

    @Test
    public void testFormat() {
        final ByteArrayOutputStream bos = new ByteArrayOutputStream(1024);
        final PrintStream out = new PrintStream(bos);
        try { job.printTo(out); }
        finally { out.close(); } // for educational purposes
        assertEquals(string, bos.toString());
    }
}
